### ISSUE TITLE
Redirect throught geo localization

### ISSUE THREAD

**Issue by theRAGEhero** [floschliep/YOURLS-Amazon-Affiliate#4]
Hi, thank you for this plugin.
At the beginning I thought it was redirecting to the country of provenience of the client ip, but it seems it isn't.

Would it be possible to add this function? Maybe something like this https://github.com/boxedfish/yourls-Geo-API-plugin/blob/master/geo_api/plugin.php. 

The idea is that if I share a link to shortened link to amazon.it and a german guy click on the link, Yourls checks the location and then redirect to amazon.de and add the german affiliate code.

Thank you and have a good day,
Alessandro

**Comment by floschliep** [comment]
Hi @theRAGEhero,

thanks for the suggestion, but I don't have plans for adding this functionality to the plugin. Feel free to open a PR yourself or fork the repo if you need this in your YOURLS.
